import os


SAMPLES_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "samples")
TEMP_TEST_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "temp")


SAMPLES_JOURNAL = {
    "v64": [{"_": "spm@insp3.insp.mx"}],
    "v490": [{"_": "Cuernavaca"}],
    "created_at": "1999-06-08",
    "v941": [{"_": "20170220"}],
    "v951": [{"_": "sonia.reis"}],
    "v6": [{"_": "c"}],
    "v330": [{"_": "CT"}],
    "collection": "spa",
    "v150": [{"_": "Salud pública Méx"}],
    "v66": [{"_": "art"}],
    "v540": [
        {
            "t": '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.',
            "_": "",
            "l": "en",
        },
        {
            "t": '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.',
            "_": "",
            "l": "es",
        },
        {
            "t": '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.',
            "_": "",
            "l": "pt",
        },
    ],
    "v854": [{"_": "Health Policy & Services"}],
    "v310": [{"_": "MX"}],
    "v67": [{"_": "na"}],
    "v943": [{"_": "20170620"}],
    "v68": [{"_": "spm"}],
    "v63": [
        {
            "_": "Av. Universidad 655, Edificio de Gobierno, Planta Baja, Col. Santa María Ahuacatitlán, Cuernavaca, Morelos, MX, 62508, (52 73) 17-5745"
        }
    ],
    "v240": [{"_": "Salud pública Méx"}, {"_": "SPM. Salud Publica de Mexico"}],
    "v10": [{"_": "br1.1"}],
    "v480": [{"_": "Instituto Nacional de Salud Pública"}],
    "issns": ["0036-3634"],
    "v450": [
        {"_": "CURRENT CONTENTS/SOCIAL AND BEHAVIORAL SCIENCES"},
        {"_": "SOCIAL SCIENCES CITATION INDEX"},
        {"_": "RESEARH ALERT"},
        {"_": "INDEX MEDICUS"},
        {"_": "INDEX MEDICUS LATINOAMERICANO"},
        {"_": "EMBASE/EXCERPTA MEDICA"},
        {"_": "CAB HEALTH/CAB ABSTRACT"},
        {"_": "EUROPEAN CLEARING HOUSE ON HEALTH SYSTEMS REFORMS"},
        {
            "_": "INDICE DE REVISTAS MEXICANAS DE INVESTIGACIÓN CIENTÍFICA Y TECNOLÓGICA DEL CONACYT"
        },
        {"_": "BIBLIOMEX-SALUD"},
        {"_": "PERIÓDICA"},
        {
            "_": "INDICE DE REVISTAS DE EDUCACIÓN SUPERIOR E INVESTIGACIÓN EDUCATIVA (IRESIE)"
        },
        {"_": "MEDLINE"},
        {"_": "LILACS"},
        {"_": "ARTEMISA"},
    ],
    "v50": [{"_": "C"}],
    "v992": [{"_": "spa"}],
    "v303": [{"_": "1"}],
    "v85": [{"_": "nd"}],
    "v541": [{"_": "BY-NC-SA/4.0"}],
    "v35": [{"_": "PRINT"}],
    "v302": [{"_": "1"}],
    "v301": [{"_": "1959"}],
    "v380": [{"_": "B"}],
    "v441": [{"_": "Health Sciences"}],
    "v935": [{"_": "0036-3634"}],
    "v100": [{"_": "Salud Pública de México"}],
    "v901": [
        {
            "_": "To publish articles both in English and Spanish related to public health topics, in the form of full-length original research papers, brief communications, review articles, essays, updates, classics, indicators, health news, book reviews and letters to the editor. Bi-monthly publication.",
            "l": "en",
        },
        {
            "_": "Publicar textos, em espanhol e em inglês, sobre temas relacionados com a saúde pública, na forma de editoriais, artigos originais, comunicações breves, artigos de revisão, ensaios, atualizações, clássicos, indicadores, notícias, resenhas bibliográficas e cartas ao editor. Publicação bimestral.",
            "l": "pt",
        },
        {
            "_": "Publicar textos, en español y en inglés, sobre temas relacionados con la salud pública, en forma de editoriales, artículos originales, breves, y de revisión, ensayos, actualizaciones, clásicos, indicadores, noticias, reseñas bibliográficas y cartas al editor. Publicación bimestral.",
            "l": "es",
        },
    ],
    "v151": [{"_": "Salud pública Méx"}],
    "v350": [{"_": "en"}, {"_": "es"}],
    "scimago_id": "19317",
    "code": "0036-3634",
    "v140": [{"_": "Instituto Nacional de Salud Publica (INSP)"}],
    "v421": [{"_": "Salud Publica Mex."}],
    "v930": [{"_": "spm"}],
    "v435": [{"t": "PRINT", "_": "0036-3634"}],
    "v230": [{"_": "Public Health of Mexico"}],
    "v320": [{"_": "Morelos"}],
    "v440": [{"_": "SAUDE PUBLICA"}],
    "v950": [{"_": "sonia.reis"}],
    "v400": [{"_": "0036-3634"}],
    "v940": [{"_": "19990608"}],
    "updated_at": "2017-08-10",
    "v5": [{"_": "S"}],
    "updated_date": "2016-05-24",
    "v62": [{"_": "Instituto Nacional de Salud Pública"}],
    "v117": [{"_": "vancouv"}],
    "v51": [{"a": "20010101", "b": "C", "_": "", "d": "C", "c": "20010701"}],
    "processing_date": "2017-02-20",
    "v880": [{"_": "0036-3634"}],
    "v69": [{"_": "http://saludpublica.mx/insp/index.php/spm"}],
    "v942": [{"_": "19990608"}],
}

SAMPLES_ARTICLE = {
    "sent_wos": "False",
    "validated_scielo": "False",
    "fulltexts": {
        "html": {
            "es": "http://www.scielosp.org/scielo.php?script=sci_arttext&pid=S0036-36341997000100001&tlng=es"
        }
    },
    "title": {
        "v35": [{"_": "PRINT"}],
        "v62": [{"_": "Instituto Nacional de Salud P\u00fablica"}],
        "v51": [{"a": "20010101", "b": "C", "d": "C", "_": "", "c": "20010701"}],
        "v5": [{"_": "S"}],
        "issns": ["0036-3634"],
        "v450": [
            {"_": "CURRENT CONTENTS/SOCIAL AND BEHAVIORAL SCIENCES"},
            {"_": "SOCIAL SCIENCES CITATION INDEX"},
            {"_": "RESEARH ALERT"},
            {"_": "INDEX MEDICUS"},
            {"_": "INDEX MEDICUS LATINOAMERICANO"},
            {"_": "EMBASE/EXCERPTA MEDICA"},
            {"_": "CAB HEALTH/CAB ABSTRACT"},
            {"_": "EUROPEAN CLEARING HOUSE ON HEALTH SYSTEMS REFORMS"},
            {
                "_": "INDICE DE REVISTAS MEXICANAS DE INVESTIGACI\u00d3N CIENT\u00cdFICA Y TECNOL\u00d3GICA DEL CONACYT"
            },
            {"_": "BIBLIOMEX-SALUD"},
            {"_": "PERI\u00d3DICA"},
            {
                "_": "INDICE DE REVISTAS DE EDUCACI\u00d3N SUPERIOR E INVESTIGACI\u00d3N EDUCATIVA (IRESIE)"
            },
            {"_": "MEDLINE"},
            {"_": "LILACS"},
            {"_": "ARTEMISA"},
        ],
        "v117": [{"_": "vancouv"}],
        "v303": [{"_": "1"}],
        "v67": [{"_": "na"}],
        "v85": [{"_": "nd"}],
        "v935": [{"_": "0036-3634"}],
        "v951": [{"_": "sonia.reis"}],
        "v63": [
            {
                "_": "Av. Universidad 655, Edificio de Gobierno, Planta Baja, Col. Santa Mar\u00eda Ahuacatitl\u00e1n, Cuernavaca, Morelos, MX, 62508, (52 73) 17-5745"
            }
        ],
        "v942": [{"_": "19990608"}],
        "v480": [{"_": "Instituto Nacional de Salud P\u00fablica"}],
        "v140": [{"_": "Instituto Nacional de Salud Publica (INSP)"}],
        "updated_date": "2016-05-24",
        "v150": [{"_": "Salud p\u00fablica M\u00e9x"}],
        "v992": [{"_": "spa"}],
        "v440": [{"_": "SAUDE PUBLICA"}],
        "v880": [{"_": "0036-3634"}],
        "v68": [{"_": "spm"}],
        "v301": [{"_": "1959"}],
        "v310": [{"_": "MX"}],
        "v64": [{"_": "spm@insp3.insp.mx"}],
        "scimago_id": "19317",
        "collection": "spa",
        "code": "0036-3634",
        "v901": [
            {
                "_": "To publish articles both in English and Spanish related to public health topics, in the form of full-length original research papers, brief communications, review articles, essays, updates, classics, indicators, health news, book reviews and letters to the editor. Bi-monthly publication.",
                "l": "en",
            },
            {
                "_": "Publicar textos, em espanhol e em ingl\u00eas, sobre temas relacionados com a sa\u00fade p\u00fablica, na forma de editoriais, artigos originais, comunica\u00e7\u00f5es breves, artigos de revis\u00e3o, ensaios, atualiza\u00e7\u00f5es, cl\u00e1ssicos, indicadores, not\u00edcias, resenhas bibliogr\u00e1ficas e cartas ao editor. Publica\u00e7\u00e3o bimestral.",
                "l": "pt",
            },
            {
                "_": "Publicar textos, en espa\u00f1ol y en ingl\u00e9s, sobre temas relacionados con la salud p\u00fablica, en forma de editoriales, art\u00edculos originales, breves, y de revisi\u00f3n, ensayos, actualizaciones, cl\u00e1sicos, indicadores, noticias, rese\u00f1as bibliogr\u00e1ficas y cartas al editor. Publicaci\u00f3n bimestral.",
                "l": "es",
            },
        ],
        "v230": [{"_": "Public Health of Mexico"}],
        "updated_at": "2017-08-10",
        "v6": [{"_": "c"}],
        "v441": [{"_": "Health Sciences"}],
        "v330": [{"_": "CT"}],
        "v380": [{"_": "B"}],
        "v540": [
            {
                "t": '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.',
                "_": "",
                "l": "en",
            },
            {
                "t": '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.',
                "_": "",
                "l": "es",
            },
            {
                "t": '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.',
                "_": "",
                "l": "pt",
            },
        ],
        "v435": [{"t": "PRINT", "_": "0036-3634"}],
        "v930": [{"_": "spm"}],
        "v541": [{"_": "BY-NC-SA/4.0"}],
        "v950": [{"_": "sonia.reis"}],
        "v854": [{"_": "Health Policy & Services"}],
        "v943": [{"_": "20170620"}],
        "v350": [{"_": "en"}, {"_": "es"}],
        "v400": [{"_": "0036-3634"}],
        "v100": [{"_": "Salud P\u00fablica de M\u00e9xico"}],
        "v69": [{"_": "http://saludpublica.mx/insp/index.php/spm"}],
        "v320": [{"_": "Morelos"}],
        "v941": [{"_": "20170220"}],
        "v10": [{"_": "br1.1"}],
        "v940": [{"_": "19990608"}],
        "v240": [
            {"_": "Salud p\u00fablica M\u00e9x"},
            {"_": "SPM. Salud Publica de Mexico"},
        ],
        "created_at": "1999-06-08",
        "processing_date": "2017-02-20",
        "v66": [{"_": "art"}],
        "v302": [{"_": "1"}],
        "v421": [{"_": "Salud Publica Mex."}],
        "v50": [{"_": "C"}],
        "v151": [{"_": "Salud p\u00fablica M\u00e9x"}],
        "v490": [{"_": "Cuernavaca"}],
    },
    "created_at": "2001-08-08",
    "body": {
        "es": '<!--version=html--> <p align="center">\u00a0</p>      <p align="center"><font size="4"><strong>EDITORIAL</strong></font></p>      <p align="center">\u00a0</p>      <p align="center">\u00a0</p>      <p><font size="5"><strong>E</strong></font>ste es el primer n\u00famero de una nueva \u00e9poca dentro de <i>Salud P\u00fablica de M\u00e9xico. </i>Fundada en 1959, la revista ha sufrido transformaciones en contenido y enfoque; de un \u00f3rgano de divulgaci\u00f3n de la Secretar\u00eda de Salud, fue haci\u00e9ndose crecientemente m\u00e1s acad\u00e9mica. En el momento actual, contamos con un Comit\u00e9 Editorial de 33 distinguidos acad\u00e9micos, 36% de los cuales son internacionales.</p>      <p>La nueva \u00e9poca de la revista <i>Salud P\u00fablica de M\u00e9xico </i>va mucho m\u00e1s all\u00e1 de un cambio cosm\u00e9tico en el dise\u00f1o gr\u00e1fico. Ahora contamos con editor cient\u00edfico, gerente editorial, editor ejecutivo y editores de secci\u00f3n.</p>      <p>Nuestra meta es ser la mejor revista de nuestro campo en Am\u00e9rica Latina para el a\u00f1o 2000. Para ello deberemos superar obst\u00e1culos de diversa naturaleza. Los indicadores actuales que miden la calidad de una revista se basan, en parte, en la frecuencia con que los art\u00edculos cient\u00edficos de la misma son citados en otras revistas cient\u00edficas.</p>      <p>Una revista de salud p\u00fablica que se edita en espa\u00f1ol tiene en s\u00ed dos desventajas inmediatas para alcanzar un buen \u00edndice de impacto: en primer lugar, el campo mismo de la salud p\u00fablica ocupa un espacio menor en relaci\u00f3n con el volumen total de publicaciones m\u00e9dicas. Por ende, el n\u00famero potencial de lectores que nos citen es \u00f3rdenes de magnitud menor. De igual manera, publicar en espa\u00f1ol limita la posibilidad de llegar a un p\u00fablico mayor, en un mundo donde el ingl\u00e9s es el idioma universal de la ciencia. Romper el c\u00edrculo vicioso de un escaso p\u00fablico, que conduce a que los art\u00edculos de nuestra revista sean citados con una baja frecuencia en otras publicaciones y por ende, a que sea menos atractivo para los autores enviarnos buenos trabajos, requiere de un esfuerzo grande y en varios frentes.</p>      <p>Ahora, la revista acepta tanto art\u00edculos en ingl\u00e9s como en espa\u00f1ol. Adem\u00e1s, se har\u00e1 un esfuerzo especial por tener, de todos los art\u00edculos originales, un buen resumen en ingl\u00e9s. La invitaci\u00f3n hecha a nuestro nuevo directorio y Comit\u00e9 Editorial busca hacer una revista m\u00e1s competitiva, alleg\u00e1ndonos mejores contribuciones bajo un estricto mecanismo de selecci\u00f3n por pares.</p>      <p>Un esfuerzo adicional para llegar a un mayor n\u00famero de lectores es la publicaci\u00f3n electr\u00f3nica de <i>Salud P\u00fablica de M\u00e9xico </i>en Internet. Lo anterior ya ha rendido frutos; un alto porcentaje de las consultas a la p\u00e1gina electr\u00f3nica del Instituto ( <a href="http://www.insp.mx">http://www.insp.mx</a> )\u00a0 acuden a la liga de la revista.</p>      <p>No hay que olvidar que, mas all\u00e1 de lograr muchas citas internacionales, nuestro principal objetivo es tener impacto en la salud de la poblaci\u00f3n. En efecto, publicar en el campo de la salud p\u00fablica tendr\u00eda su mayor relevancia en la modificaci\u00f3n de las pol\u00edticas o intervenciones en salud que beneficien a la poblaci\u00f3n. De ah\u00ed que nuestros principales clientes deban de ser tomadores de decisiones, acad\u00e9micos y practicantes de la salud p\u00fablica. Al emprender esta nueva fase, <i>Salud P\u00fablica de M\u00e9xico </i>se propone continuar contribuyendo en la difusi\u00f3n del conocimiento cient\u00edfico, conjugando la excelencia acad\u00e9mica con la pertinencia tem\u00e1tica.</p>      <p>\u00a0</p>      <p align="right">Jaime Sep\u00falveda*</p>      <p align="right">\u00a0</p>      <p align="right">\u00a0</p>      <p align="left">* Director General del Instituto Nacional de Salud P\u00fablica, M\u00e9xico.</p>'
    },
    "version": "html",
    "applicable": "True",
    "processing_date": "2001-08-08",
    "publication_year": "1997",
    "doi": "10.1590/S0036-36341997000100001",
    "normalized": {"article": {"v70": {"p": [True]}}},
    "license": "by/3.0",
    "issue": {
        "created_at": "2001-08-08",
        "processing_date": "2001-08-08",
        "issue": {
            "v43": [
                {
                    "m": "ene./feb.",
                    "n": "n.1",
                    "l": "es",
                    "t": "Salud p\u00fablica M\u00e9x",
                    "_": "",
                    "v": "v.39",
                    "a": "1997",
                    "c": "Cuernavaca",
                },
                {
                    "m": "jan./fev.",
                    "n": "n.1",
                    "l": "pt",
                    "t": "Salud p\u00fablica M\u00e9x",
                    "_": "",
                    "v": "v.39",
                    "a": "1997",
                    "c": "Cuernavaca",
                },
                {
                    "m": "Jan./Feb.",
                    "n": "n.1",
                    "l": "en",
                    "t": "Salud p\u00fablica M\u00e9x",
                    "_": "",
                    "v": "vol.39",
                    "a": "1997",
                    "c": "Cuernavaca",
                },
            ],
            "v35": [{"_": "0036-3634"}],
            "v4": [{"_": "v39n1"}],
            "v117": [{"_": "other"}],
            "v130": [{"_": "Salud P\u00fablica de M\u00e9xico"}],
            "v85": [{"_": "nd"}],
            "v151": [{"_": "Salud p\u00fablica M\u00e9x"}],
            "v65": [{"_": "19970100"}],
            "v480": [{"_": "Instituto Nacional de Salud P\u00fablica"}],
            "v48": [
                {"_": "", "h": "Sumario", "l": "es"},
                {"_": "", "h": "Sum\u00e1rio", "l": "pt"},
                {"_": "", "h": "Table of Contents", "l": "en"},
            ],
            "v36": [{"_": "19971"}],
            "v706": [{"_": "i"}],
            "v992": [{"_": "spa"}],
            "v91": [{"_": "20010808"}],
            "v49": [
                {"t": "Art\u00edculos originales", "_": "", "l": "es", "c": "SPM010"},
                {"t": "Ensayos", "_": "", "l": "es", "c": "SPM030"},
                {"t": "Actualizaciones", "_": "", "l": "es", "c": "SPM040"},
                {"t": "Art\u00edculos especiales", "_": "", "l": "es", "c": "SPM050"},
                {"t": "Indicadores", "_": "", "l": "es", "c": "SPM060"},
                {"t": "Editorial", "_": "", "l": "es", "c": "SPM070"},
                {"t": "Art\u00edculos breves", "_": "", "l": "es", "c": "SPM150"},
                {"t": "Original articles", "_": "", "l": "en", "c": "SPM010"},
                {"t": "Essays", "_": "", "l": "en", "c": "SPM030"},
                {"t": "Updates", "_": "", "l": "en", "c": "SPM040"},
                {"t": "Special articles", "_": "", "l": "en", "c": "SPM050"},
                {"t": "Indicators", "_": "", "l": "en", "c": "SPM060"},
                {"t": "Editorial", "_": "", "l": "en", "c": "SPM070"},
                {"t": "Short papers", "_": "", "l": "en", "c": "SPM150"},
            ],
            "v880": [{"_": "0036-363419970001"}],
            "v930": [{"_": "SPM"}],
            "v200": [{"_": "1"}],
            "v42": [{"_": "1"}],
            "v30": [{"_": "Salud p\u00fablica M\u00e9x"}],
            "v991": [{"_": "1"}],
            "v701": [{"_": "1"}],
            "v32": [{"_": "1"}],
            "v122": [{"_": "15"}],
            "v31": [{"_": "39"}],
            "v700": [{"_": "0"}],
            "v421": [{"_": "Salud p\u00fablica M\u00e9x"}],
            "v230": [{"_": "Public Health of Mexico"}],
            "v6": [{"_": "001"}],
        },
        "collection": "spa",
        "code": "0036-363419970001",
        "issue_type": "regular",
        "publication_date": "1997-01",
        "code_title": ["0036-3634"],
        "publication_year": "1997",
        "_shard_id": "d8d458a8197b42daab954c529654a786",
    },
    "code_issue": "0036-363419970001",
    "collection": "spa",
    "code": "S0036-36341997000100001",
    "citations": [],
    "code_title": ["0036-3634"],
    "document_type": "editorial",
    "article": {
        "v123": [{"_": "2"}],
        "v35": [{"_": "0036-3634"}],
        "v38": [{"_": "ND"}],
        "v708": [{"_": "1"}],
        "v702": [{"_": "C:\\SciELO\\Serial\\spm\\v39n1\\markup\\edit.htm"}],
        "v992": [{"_": "spa"}],
        "v120": [{"_": "3.0"}],
        "v977": [{"_": "EDITORIAL", "l": "es"}],
        "v12": [{"_": "EDITORIAL", "l": "es"}],
        "v65": [{"_": "19970100"}],
        "v936": [{"i": "0036-3634", "o": "1", "y": "1997", "_": ""}],
        "v1": [{"_": "br1.1"}],
        "v706": [{"_": "h"}],
        "v121": [{"_": "01"}],
        "v2": [{"_": "S0036-3634(97)03900101"}],
        "v91": [{"_": "20010808"}],
        "v709": [{"_": "text"}],
        "v49": [{"_": "SPM070"}],
        "v880": [{"_": "S0036-36341997000100001"}],
        "v40": [{"_": "es"}],
        "v705": [{"_": "S"}],
        "v10": [{"1": "A01", "s": "Sep\u00falveda", "n": "Jaime", "r": "ND", "_": ""}],
        "v14": [{"_": "", "f": "1", "l": "1"}],
        "v42": [{"_": "1"}],
        "v30": [{"_": "Salud p\u00fablica M\u00e9x"}],
        "v70": [
            {"i": "A01", "_": "Instituto Nacional de Salud P\u00fablica", "p": "Mexico"}
        ],
        "v701": [{"_": "1"}],
        "v32": [{"_": "1"}],
        "v71": [{"_": "ed"}],
        "v700": [{"_": "2"}],
        "v158": [{"_": "nd"}],
        "v4": [{"_": "v39n1"}],
        "v31": [{"_": "39"}],
        "v882": [{"_": "", "n": "1", "v": "39"}],
    },
    "updated_at": "2017-08-29",
    "validated_wos": "False",
    "section": {"en": "Editorial", "es": "Editorial"},
}

SAMPLES_XML_ARTICLE = open(
    os.path.join(SAMPLES_PATH, "S0036-36341997000100001.xml"), "r"
).read()

SAMPLE_KERNEL_JOURNAL = {
    "created": "2019-01-28T00:00:00.000000Z",
    "updated": "2019-01-28T00:00:00.000000Z",
    "items": [],
    "metadata": {
        "title": [["2019-01-28T00:00:00.000000Z", "sample"]],
        "acronym": [["2019-01-28T00:00:00.000000Z", "spl"]],
        "status": [["2019-01-28T00:00:00.000000Z", {"status": "current"}]],
        "scielo_issn": [["2019-01-28T00:00:00.000000Z", "0001-3714"]],
        "electronic_issn": [["2019-01-28T00:00:00.000000Z", "0001-3714"]],
    },
    "id": "0001-3714",
    "_id": "0001-3714",
}

SAMPLE_JOURNALS_JSON = [
    {
        "v100": [{"_": "sample"}],
        "v68": [{"_": "spl"}],
        "v940": [{"_": "20190128"}],
        "v50": [{"_": "C"}],
        "v400": [{"_": "0001-3714"}],
        "v435": [{"t": "ONLIN", "_": "0001-3714"}],
    }
]

SAMPLE_ISSUES_JSON = [
    {
        "v6": [{"_": "001"}],
        "v122": [{"_": "16"}],
        "v130": [{"_": "Revista de Microbiologia"}],
        "v230": [{"_": "Journal of the Brazilian Society for Microbiology"}],
        "v91": [{"_": "19990226"}],
        "v706": [{"_": "i"}],
        "v30": [{"_": "Rev. Microbiol."}],
        "mfn": 1,
        "v701": [{"_": "1"}],
        "v32": [{"_": "3"}],
        "v43": [
            {
                "a": "1998",
                "c": "São Paulo",
                "l": "pt",
                "m": "Set.",
                "n": ["n. 3"],
                "t": "Rev. Microbiol.",
                "v": ["v. 29"],
            },
            {
                "a": "1998",
                "c": "São Paulo",
                "l": "en",
                "m": "Sept.",
                "n": ["n. 3"],
                "t": "Rev. Microbiol.",
                "v": ["vol. 29"],
            },
            {
                "a": "1998",
                "c": "São Paulo",
                "l": "es",
                "m": "Sept.",
                "n": ["n. 3"],
                "t": "Rev. Microbiol.",
                "v": ["v. 29"],
            },
        ],
        "v65": [{"_": "19980900"}],
        "v31": [{"_": "29"}],
        "v42": [{"_": "1"}],
        "v64": [{"a": "1998", "m": "09"}],
        "v930": [{"_": "RM"}],
        "v700": [{"_": "0"}],
        "v36": [{"_": "19983"}],
        "v35": [{"_": "0001-3714"}],
        "v49": [
            {"c": "RM110", "l": "en", "t": "Soil and Environmental Microbiology"},
            {"c": "RM090", "l": "en", "t": "Medical Microbiology"},
            {"c": "RM060", "l": "en", "t": "Micology"},
            {"c": "RM020", "l": "en", "t": "Industrial Microbiology"},
            {"c": "RM080", "l": "en", "t": "Virology"},
            {"c": "RM120", "l": "en", "t": "Food Microbiology"},
            {"c": "RM030", "l": "en", "t": "Veterinarian Microbiology"},
            {"c": "RM100", "l": "en", "t": "Errata"},
        ],
        "v48": [
            {"h": ["Sumário"], "l": "pt"},
            {"h": ["Table of Contents"], "l": "en"},
            {"h": ["Sumario"], "l": "es"},
        ],
    }
]

SAMPLE_ISSUES_KERNEL = [
    {
        "created": "1998-09-01T00:00:00.000000Z",
        "updated": "1998-09-01T00:00:00.000000Z",
        "items": [],
        "metadata": {
            "publication_year": [["1998-09-01T00:00:00.000000Z", "1998"]],
            "publication_month": [["1998-09-01T00:00:00.000000Z", "9"]],
            "volume": [["1998-09-01T00:00:00.000000Z", "29"]],
            "number": [["1998-09-01T00:00:00.000000Z", "3"]],
            "publication_season": [["1998-09-01T00:00:00.000000Z", [9]]],
        },
        "_id": "0001-3714-1998-v29-n3",
        "id": "0001-3714-1998-v29-n3",
    }
]

SAMPLE_AOPS_KERNEL = [
    {
        "created": "1998-09-01T00:00:00.000000Z",
        "updated": "1998-09-01T00:00:00.000000Z",
        "items": [],
        "metadata": {},
        "_id": "0001-3714-aop",
        "id": "0001-3714-aop",
    }
]
COUNT_SAMPLES_FILES = 13
